[database]
    username="root"
    password="123"
    host="localhost"
    port=3306
    dbName="test"
    [redis.pool]
        initSize = 3
        maxSize = 20
        idleTimeOut = 60

[redis]
    host="localhost"
    port=6379
    password=""
    [redis.pool]
        initSize = 3
        maxSize = 50
        maxIdle = 10
        idleTimeOut = 60

[mongodb]
    addresses=[
        "localhost:27017"
    ]
    username="wangyalou"
    password="123"
    dbName="test"
    use_secondary_read=true
    replicaSet="dev_replica"
    [mongodb.pool]
        initSize = 1
        maxSize = 80
        maxIdle = 10
        idleTimeOut = 60

[logstash]
    host="localhost"
    port=7000

[fileserver]
    endpoint="http://oss-cn-hangzhou.aliyuncs.com"
    accessKey="123"
    accessKeySecret="12345"
    [fileserver.pool]
        initSize = 1
        maxSize = 80
        maxIdle = 10
        idleTimeOut = 60
